# -*- coding: utf-8 -*-
# @createTime    : 2019/5/20 11:28
# @author  : Huanglg
# @fileName: 123.py
# @email: luguang.huang@mabotech.com
str = """[{\"StationId\":\"stationId\",\"OrderId\":\"orderId\",\"StateCode\":1,\"ErrorInfo\":\"errorArray[i]\",\"OccurTime\":\"2019-05-20 11:09\",\"StateItems\":[]},{\"StationId\":\"stationId\",\"OrderId\":\"orderId\",\"StateCode\":1,\"ErrorInfo\":\"errorArray[i]\",\"OccurTime\":\"2019-05-20 11:09\",\"StateItems\":[]},{\"StationId\":\"stationId\",\"OrderId\":\"orderId\",\"StateCode\":1,\"ErrorInfo\":\"errorArray[i]\",\"OccurTime\":\"2019-05-20 11:09\",\"StateItems\":[]},{\"StationId\":\"stationId\",\"OrderId\":\"orderId\",\"StateCode\":1,\"ErrorInfo\":\"errorArray[i]\",\"OccurTime\":\"2019-05-20 11:09\",\"StateItems\":[]},{\"StationId\":\"stationId\",\"OrderId\":\"orderId\",\"StateCode\":1,\"ErrorInfo\":\"errorArray[i]\",\"OccurTime\":\"2019-05-20 11:09\",\"StateItems\":[]},{\"StationId\":\"stationId\",\"OrderId\":\"orderId\",\"StateCode\":1,\"ErrorInfo\":\"errorArray[i]\",\"OccurTime\":\"2019-05-20 11:09\",\"StateItems\":[]},{\"StationId\":\"stationId\",\"OrderId\":\"orderId\",\"StateCode\":1,\"ErrorInfo\":\"errorArray[i]\",\"OccurTime\":\"2019-05-20 11:09\",\"StateItems\":[]},{\"StationId\":\"stationId\",\"OrderId\":\"orderId\",\"StateCode\":1,\"ErrorInfo\":\"errorArray[i]\",\"OccurTime\":\"2019-05-20 11:09\",\"StateItems\":[]},{\"StationId\":\"stationId\",\"OrderId\":\"orderId\",\"StateCode\":1,\"ErrorInfo\":\"errorArray[i]\",\"OccurTime\":\"2019-05-20 11:09\",\"StateItems\":[]},{\"StationId\":\"stationId\",\"OrderId\":\"orderId\",\"StateCode\":1,\"ErrorInfo\":\"errorArray[i]\",\"OccurTime\":\"2019-05-20 11:09\",\"StateItems\":[]},{\"StationId\":\"stationId\",\"OrderId\":\"orderId\",\"StateCode\":1,\"ErrorInfo\":\"errorArray[i]\",\"OccurTime\":\"2019-05-20 11:09\",\"StateItems\":[]}]"""
import json
res = json.loads(str)
list1 = [{'StationId': 'stationId', 'OrderId': 'orderId', 'StateCode': 1, 'ErrorInfo': 'errorArray[i]', 'OccurTime': '2019-05-20 11:09', 'StateItems': []}, {'StationId': 'stationId', 'OrderId': 'orderId', 'StateCode': 1, 'ErrorInfo': 'errorArray[i]', 'OccurTime': '2019-05-20 11:09', 'StateItems': []}, {'StationId': 'stationId', 'OrderId': 'orderId', 'StateCode': 1, 'ErrorInfo': 'errorArray[i]', 'OccurTime': '2019-05-20 11:09', 'StateItems': []}, {'StationId': 'stationId', 'OrderId': 'orderId', 'StateCode': 1, 'ErrorInfo': 'errorArray[i]', 'OccurTime': '2019-05-20 11:09', 'StateItems': []}, {'StationId': 'stationId', 'OrderId': 'orderId', 'StateCode': 1, 'ErrorInfo': 'errorArray[i]', 'OccurTime': '2019-05-20 11:09', 'StateItems': []}, {'StationId': 'stationId', 'OrderId': 'orderId', 'StateCode': 1, 'ErrorInfo': 'errorArray[i]', 'OccurTime': '2019-05-20 11:09', 'StateItems': []}, {'StationId': 'stationId', 'OrderId': 'orderId', 'StateCode': 1, 'ErrorInfo': 'errorArray[i]', 'OccurTime': '2019-05-20 11:09', 'StateItems': []}, {'StationId': 'stationId', 'OrderId': 'orderId', 'StateCode': 1, 'ErrorInfo': 'errorArray[i]', 'OccurTime': '2019-05-20 11:09', 'StateItems': []}, {'StationId': 'stationId', 'OrderId': 'orderId', 'StateCode': 1, 'ErrorInfo': 'errorArray[i]', 'OccurTime': '2019-05-20 11:09', 'StateItems': []}, {'StationId': 'stationId', 'OrderId': 'orderId', 'StateCode': 1, 'ErrorInfo': 'errorArray[i]', 'OccurTime': '2019-05-20 11:09', 'StateItems': []}, {'StationId': 'stationId', 'OrderId': 'orderId', 'StateCode': 1, 'ErrorInfo': 'errorArray[i]', 'OccurTime': '2019-05-20 11:09', 'StateItems': []}]
for item in list1:
    print(item)

